### ISSUE TITLE
Cant find the body feet extractor .tar file. ('../body_model.pth.tar') can you please share the link

### ISSUE THREAD

**Issue by Syedwajihshah** [rash1993/movie-asd#6]

**Comment by Syedwajihshah** [comment]
Never mind. I missed a step. :)

**Comment by xiaohaook** [comment]
Could you restore the public download for `body_model.pth.tar`, or provide an official mirror?

I am reproducing the `--talknet --diarize` path at commit `1cc3f1632222ea77d88da08b03dcce9003d3a55e`. The `setup.sh` body-checkpoint link (Google Drive ID `1kqEO-EKT4l70S-gnd7UJoMwWy6lToQSe`) fails with gdown, and its public file page returned HTTP 404 on 2026-09-15:
https://drive.google.com/file/d/1kqEO-EKT4l70S-gnd7UJoMwWy6lToQSe/view

The fresh-cache path calls `VideoPreProcessor.run()` → `getBodyTrackEmbeddings()` → `Extractor`, which loads this checkpoint. I have not skipped this stage or substituted another ReID model.

If available, please also share the checkpoint SHA256 and training/model provenance so a recovered file can be verified against this implementation. The original introducing commit and the diarize branch point to the same Drive ID.

This request concerns the missing published asset, not an inference-quality result. Thank you.
